### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by rjbenson01** [rayokota/generator-angular-express-sequelize#9]
Looking for a MEANjs alternative that uses mysql (or sequalizer) instead of Mongodb. Yet every project/generator for this type of project is either poorly constructed or abandoned.

Is it truly so difficult to replace mongodb with a relationshal db using yeoman??

**Comment by rayokota** [comment]
If you don't want to use this generator, you can look at https://github.com/DaftMonk/generator-angular-fullstack/issues/414
